export const data = [
    {
        id: 1,
        "Image": "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UY209_CR0,0,140,209_AL_.jpg",

        "Title": "Batman: Vạch Trần Sự Thật",
        "des": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 2,
        "Image": "https://m.media-amazon.com/images/M/MV5BMWFmYmRiYzMtMTQ4YS00NjA5LTliYTgtMmM3OTc4OGY3MTFkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY209_CR13,0,140,209_AL_.jpg",
        "Title": " Avatar: Dòng Chảy Của Nước",
        "des": "Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their planet.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 3,
        "Image": "https://m.media-amazon.com/images/M/MV5BZjRjMzIxODEtZTY5NS00YWMxLTgzOGEtNmUzMzNjNWRhZThlXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "Title": "Kẻ Đâm Lén: Glass Onion",
        "des": "Famed Southern detective Benoit Blanc travels to Greece for his latest case.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 4,
        "Image": "https://m.media-amazon.com/images/M/MV5BMWM5YTRlNjYtNGRlMy00M2U5LTgyMTItMmFhODUzNDcxMWVhXkEyXkFqcGdeQXVyMjU5OTg0MTQ@._V1_UY209_CR14,0,140,209_AL_.jpg",
        "Title": "Argylle",
        "des": "The world's greatest spy, 'Argylle,' gets caught up in a globe-trotting adventure.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 5,
        "Image": "https://m.media-amazon.com/images/M/MV5BZmMyMDc4NWMtZmUzNC00ZjczLWE1ZmYtYWQ3ZTk4ODBmYzE2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY209_CR87,0,140,209_AL_.jpg",
        "Title": "Killers of the Flower Moon",
        "des": "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s sparking a major F.B.I. investigation involving J. Edgar Hoover.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 6,
        "Image": "https://m.media-amazon.com/images/M/MV5BZGRhNDE1YjYtOGUzMC00YjliLThiOTgtYTkwNmQwNDZjYjFhXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UY209_CR0,0,140,209_AL_.jpg",
        "Title": " Spider-Man: Across the Spider-Verse",
        "des": "Miles Morales returns for the next chapter of the Oscar®-winning Spider-Verse saga, an epic adventure that will transport Brooklyn's full-time",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 7,
        "Image": "https://m.media-amazon.com/images/M/MV5BYzMzNTJjYmMtZTkxNS00MjI4LWI3YmQtOTQ4MDZjZDJlZjQyXkEyXkFqcGdeQXVyNjc0NzQzNTM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "Title": " Elvis",
        "des": "The life of American music icon Elvis Presley, from his childhood to becoming a rock and movie star in the 1950s while maintaining a complex relationship with his manager, Colonel Tom Parker.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 8,
        "Image": "https://m.media-amazon.com/images/M/MV5BZmM4MWIwMGItYzA3ZC00MDY4LTlhNWQtY2MwOTViODk1M2U1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UY209_CR0,0,140,209_AL_.jpg",
        "Title": " Babylon",
        "des": "Set in Hollywood during the transition from silent films to talkies, focusing on a mixture of historical & fictional characters.",
        "Year": "1977",
        "Nation": "USA",
    },
    {
        id: 9,
        "Image": "https://m.media-amazon.com/images/M/MV5BMzM3Y2JlMDMtM2E0Ny00YjA5LWJkOTYtNzk2OWY3NGE0YjBmXkEyXkFqcGdeQXVyMTMxNTMyNDQw._V1_UX140_CR0,0,140,209_AL_.jpg",
        "Title": " Sherlock Holmes 3",
        "des": "The plot is unknown at this time.",
        "Year": "1977",
        "Nation": "USA",
    },
]